export class JobView{
    JobId:number;
    AreaName:string;
    CityName:string;
    WSName:string;
    CompanyName:string;
    PartName:string;
    SubjectName:string;
    OutNetName:string;
    JobDateAdv:Date;
    JobDateCaughtJob:Date;
    JobDateShow:string;
    JobDescribe:string;
    JobStars:number;
    JobExperience:number;
    JobRole:string;
    JobRequire:string;
    CompanyId:number;
    BossId:number;
    JobSigned:boolean=false;
}